//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerTelegramService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FarmerTelegramService.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любой тип документа.
        /// </summary>
        internal static string AnyDocType {
            get {
                return ResourceManager.GetString("AnyDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда.
        /// </summary>
        internal static string ChainNotFound {
            get {
                return ResourceManager.GetString("ChainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип документа.
        /// </summary>
        internal static string ChooseDocType {
            get {
                return ResourceManager.GetString("ChooseDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое действие, попробуйте еще раз.
        /// </summary>
        internal static string CommandIsEmpty {
            get {
                return ResourceManager.GetString("CommandIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис недоступен. Пожалуйста, попробуйте позже.
        /// </summary>
        internal static string DocApiIsUnavailable {
            get {
                return ResourceManager.GetString("DocApiIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы не найдены.
        /// </summary>
        internal static string DocsNotFound {
            get {
                return ResourceManager.GetString("DocsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечень найденных документов:.
        /// </summary>
        internal static string DocumentsList {
            get {
                return ResourceManager.GetString("DocumentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите минимальную дату документа в формате ДД.ММ.ГГГГ (напр. 27.01.2020). Если допустимо любое значение, нажмите {0}.
        /// </summary>
        internal static string EnterDateFrom {
            get {
                return ResourceManager.GetString("EnterDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите максимальную дату документа в формате ДД.ММ.ГГГГ (напр. 27.01.2020). Если допустимо любое значение, нажмите {0}.
        /// </summary>
        internal static string EnterDateTo {
            get {
                return ResourceManager.GetString("EnterDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер документа, или его часть. Если допустимо любое значение, нажмите {0}.
        /// </summary>
        internal static string EnterDocNum {
            get {
                return ResourceManager.GetString("EnterDocNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер основного договора, или его часть. Если допустимо любое значение, нажмите {0}.
        /// </summary>
        internal static string EnterMainDocNum {
            get {
                return ResourceManager.GetString("EnterMainDocNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен максимальный размер файла.
        /// </summary>
        internal static string FileIsTooBig {
            get {
                return ResourceManager.GetString("FileIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        internal static string MenuCaption {
            get {
                return ResourceManager.GetString("MenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество найденных документов превышает максимально возможное. Попробуйте сузить область поиска..
        /// </summary>
        internal static string ResultsCountIsTooBig {
            get {
                return ResourceManager.GetString("ResultsCountIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт был успешно привязан.
        /// </summary>
        internal static string SuccessfullAuthorization {
            get {
                return ResourceManager.GetString("SuccessfullAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный номер не найден.
        /// </summary>
        internal static string UnknownPhone {
            get {
                return ResourceManager.GetString("UnknownPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная последовательность. Пожалуйста, попробуйте начать заново..
        /// </summary>
        internal static string UnknownStepCode {
            get {
                return ResourceManager.GetString("UnknownStepCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствуем вас! Для привязки аккаунта telegram к аккаунту портала фермеров, пожалуйста, нажмите &quot;Отправить контактные данные&quot;.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный формат даты.
        /// </summary>
        internal static string WrongDateFormat {
            get {
                return ResourceManager.GetString("WrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешены только файлы с расширением .pdf.
        /// </summary>
        internal static string WrongExtension {
            get {
                return ResourceManager.GetString("WrongExtension", resourceCulture);
            }
        }
    }
}
